### PR TITLE
chore(npm): update deps // remove bower

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
I reran the build with the new deps (you probably want to check what changed, I assume some encoding thing, but we haven't had any issue)

This is in prep for #1 
If you update to version 1.2 then I can give you access to the currency-flag npm name and you can publish a new version (and then #1 can be closed)

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Any feedback on this? I will rebase the generated css files if the other changes look good

**Comment by AdriVanHoudt** [comment]
ping @oliverviljamaa

**Comment by AdriVanHoudt** [comment]
@oliverviljamaa should be good now

**Comment by AdriVanHoudt** [comment]
🎉 
I will give you publish rights to the npm module and then you can update the version and publish it 💪

**Comment by oliverviljamaa** [comment]
Thanks!

**Comment by AdriVanHoudt** [comment]
done, feel free to publish :shipit:

**Comment by oliverviljamaa** [comment]
bitmoji
(after accidentally publishing 0.6.1...)

**Pull request merged**
